language: python
before_install:
- sudo add-apt-repository --yes ppa:fontforge/fontforge
- sudo apt-get update -qq
- sudo apt-get install python-fontforge ttfautohint
- cp /usr/lib/python2.7/dist-packages/fontforge.* "$HOME/virtualenv/python2.7.8/lib/python2.7/site-packages"
install:
- pip install git+https://github.com/behdad/fontTools.git
- pip install git+https://github.com/googlefonts/fontcrunch.git
- pip install git+https://github.com/googlefonts/fontbakery-cli.git
- pip install jinja2
before_script:
- mkdir -p builds/build
script: PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-build.py . 2>&1 | tee -a builds/build/buildlog.txt
branches:
  only:
  - master
after_script:
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-report.py builds/build
- rm -rf builds/build/sources
- rm -rf builds/build/build.state.yaml
- PATH=/home/travis/virtualenv/python2.7.8/bin/:$PATH fontbakery-travis-deploy.py
env:
  global:
    secure: N9d/5qbcvzm+qNRJo0ZJpJamk5kJ0IEsK6Yj/FCSlJPVKzNUlp1H/Wcn9/Ih/S/vKA4EB4GnY7nJ6ME6igfw5x4pxHtihKqb3XXBu366U75n/c3KOgzeM1e47RCuQqLXsLF0gDSLMO08AWLFBmSj/t0Gybv+Dro0y2UM2TJYxmw=
